export const proposalMain = [
  {
    pubkey: "GjyRZ1gRCZbmpcJuUDgg3htRdXbyhAFE5BXFvfkhwAJr",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 3,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "soru",
      name: "af : Calll",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "02",
          voteResult: 1,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "6527f1d4",
      signingOffAt: "6527f1d4",
      votingAt: "6527f1d4",
      votingAtSlot: "0eeef909",
      votingCompletedAt: "6527f204",
      executionFlags: 0,
      maxVoteWeight: "02",
      voteThreshold: {
        type: 0,
        value: 60,
      },
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "7obQ2A5dtXRppQZJ62zzBtMsRr7r1ez7aUzkVugtnAZj",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 3,
      tokenOwnerRecord: "UsW6BHptNAVSRQjySLqbCMm16wZTH5R4Y9Df96WafUp",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "denemedeneme deneme deneme",
      name: "hshaahahha",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "02",
          voteResult: 1,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "6527f14f",
      signingOffAt: "6527f150",
      votingAt: "6527f150",
      votingAtSlot: "0eeef7a3",
      votingCompletedAt: "6527f19e",
      executionFlags: 0,
      maxVoteWeight: "02",
      voteThreshold: {
        type: 0,
        value: 60,
      },
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "GdgRw51FrH7SkQGwtXcZUsch15cj1cZJBPtpzxgtXUw1",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 2,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "ffff",
      name: "fffff",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "6529425d",
      signingOffAt: "6529425d",
      votingAt: "6529425d",
      votingAtSlot: "0ef28794",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "3An7c3i5fSHXn8Wwv86eZyE4boE4XE7f4Zj9PCxMjVEu",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 2,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "çok ama çok seçmeli",
      name: "çoktan seçmeli",
      voteType: {
        type: 1,
        choiceType: 0,
        minVoterOptions: 1,
        maxVoterOptions: 2,
        maxWinningOptions: 2,
      },
      options: [
        {
          label: "Af",
          voteWeight: "01",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
        {
          label: "Ogi",
          voteWeight: "01",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      reserved1: 0,
      draftAt: "6527f152",
      signingOffAt: "6527f156",
      votingAt: "6527f156",
      votingAtSlot: "0eeef7b2",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "2YjL9qMA9Qt6ypM82oRKQb6xJij7YcPBky4AeB28E9U6",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 0,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 0,
      signatoriesSignedOffCount: 0,
      descriptionLink: "testt",
      name: "testtt",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "652958d9",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "EKdu5ZTVa3sNoM9KU4pTKRXd4HgRV1T7Bdwdugim81kx",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 7,
      tokenOwnerRecord: "UsW6BHptNAVSRQjySLqbCMm16wZTH5R4Y9Df96WafUp",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "acaba olacak mi test deneme",
      name: "deneme yayini ",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 2,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "01",
      reserved1: 0,
      draftAt: "6527f0e8",
      signingOffAt: "6527f0e8",
      votingAt: "6527f0e8",
      votingAtSlot: "0eeef68a",
      votingCompletedAt: "6527f121",
      executionFlags: 0,
      maxVoteWeight: "02",
      voteThreshold: {
        type: 0,
        value: 60,
      },
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "DW8gJyVFs48r7mh753BiBJp3vt7xA3yRZ4Hr4WJme14S",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 0,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 0,
      signatoriesSignedOffCount: 0,
      descriptionLink: "testt",
      name: "testtt",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "652959f5",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "5PkLneD9HkbBBxC8Lb7D7TVRwMXcF9QZrAc8qnnQh6v4",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 7,
      tokenOwnerRecord: "UsW6BHptNAVSRQjySLqbCMm16wZTH5R4Y9Df96WafUp",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "deneme yes no",
      name: "yeni3-yes-no",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "01",
          voteResult: 2,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "01",
      reserved1: 0,
      draftAt: "6527f3a5",
      signingOffAt: "6527f3a5",
      votingAt: "6527f3a5",
      votingAtSlot: "0eeefdf3",
      votingCompletedAt: "6527f3ba",
      executionFlags: 0,
      maxVoteWeight: "02",
      voteThreshold: {
        type: 0,
        value: 60,
      },
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "9P4umcs3qe4fAhwRn1DJDZ66ktYctKkBtcai7GZwfjop",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 2,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "",
      name: "fffff",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "65294231",
      signingOffAt: "65294232",
      votingAt: "65294232",
      votingAtSlot: "0ef2871f",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "R1ZEFPCDa7uLQLfUTr5UUCv55QxYx63Rg8DN4eiNxMj",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 2,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "fffff",
      name: "fffffffff",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "652941dc",
      signingOffAt: "652941dc",
      votingAt: "652941dc",
      votingAtSlot: "0ef28638",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "Ea3QcVHrNUNxeJZZxTGjgzvVhzdGBgqJc6Uij85RT9sP",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 2,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "32434",
      name: "34234",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "65295e9d",
      signingOffAt: "65295e9d",
      votingAt: "65295e9d",
      votingAtSlot: "0ef2d3f6",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "9zyWb6k9CE53cdtVGfG3ydpa67JRhreB6Mh8vMqAKUY3",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 0,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 0,
      signatoriesSignedOffCount: 0,
      descriptionLink: "testt",
      name: "testtt",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "65295944",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "4eJTwTSdMsyGRpXPUioUT2by2uZBYKnxDxQeyM1aLYi2",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 0,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 0,
      signatoriesSignedOffCount: 0,
      descriptionLink: "testt",
      name: "testtt",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "6529584c",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "66eU12W9k3KyHP9AURTy1bSM8RA5R6Nkpv9hA1pQMafG",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 2,
      tokenOwnerRecord: "UsW6BHptNAVSRQjySLqbCMm16wZTH5R4Y9Df96WafUp",
      signatoriesCount: 1,
      signatoriesSignedOffCount: 1,
      descriptionLink: "heyhey",
      name: "deneme-1",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "01",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "652841c5",
      signingOffAt: "652841c6",
      votingAt: "652841c6",
      votingAtSlot: "0eefd13b",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
  {
    pubkey: "6kZA5CWwDzRUrcmXB4LhP21AjZ7ThxsNgTvsiwSeLXaf",
    account: {
      accountType: 14,
      governance: "63f7oDJFxnNjPYvDuUwtJtx2Y1UijEmqDWjJUbnHDU7c",
      governingTokenMint: "HfwmLM8CQKZKqgUy6ucJh6cM87wrRm8mRK2NEvEEg5i1",
      state: 0,
      tokenOwnerRecord: "HA3qdcPmxx9VkdziCk6dRZgxjwwuaSqU2QetDZrZaXgh",
      signatoriesCount: 0,
      signatoriesSignedOffCount: 0,
      descriptionLink: "testt",
      name: "testtt",
      voteType: {
        type: 0,
      },
      options: [
        {
          label: "Approve",
          voteWeight: "00",
          voteResult: 0,
          instructionsExecutedCount: 0,
          instructionsCount: 0,
          instructionsNextIndex: 0,
        },
      ],
      denyVoteWeight: "00",
      reserved1: 0,
      draftAt: "6529602b",
      executionFlags: 0,
      vetoVoteWeight: "00",
    },
    owner: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
  },
];
